# Generated by Django 4.0.6 on 2022-07-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_offer_user_delete_sitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=30, verbose_name='offer_title'),
        ),
    ]
