# Generated by Django 4.0.6 on 2022-07-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='published_date',
        ),
    ]
